### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by beatgammit** [mattn/go-mjpeg#1]
I don't see a license here, which means I can't use this for commercial work. If it's alright with you, I'd prefer MIT, Apache-2.0, BSD or some other liberal license.

**Comment by mattn** [comment]
MIT.I'll add LICENSE in later.

On 2/25/17, Jameson Little <notifications@github.com> wrote:
> I don't see a license here, which means I can't use this for commercial
> work. If it's alright with you, I'd prefer MIT, Apache-2.0, BSD or some
> other liberal license.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mattn/go-mjpeg/issues/1


-- 
- Yasuhiro Matsumoto

**Comment by mattn** [comment]
added
