### ISSUE TITLE
Add documentation for NewDecoder

### ISSUE THREAD

**Issue by plutov** [mattn/go-mjpeg#2]
Seems I can use this package to decode Motion-JPEG from Raspberry Pi V4L2, but what value should I send to second argument `boundary`? Will be good to have it in func docs. Thanks!

**Comment by mattn** [comment]
It is boundary string of HTTP multi-part. multi-part is separated with `-- your-boundary-string`. This is generated from the server.

**Comment by mattn** [comment]
Most of case, you can use NewDecoderFromResponse or NewDecoderFromURL.
